### ISSUE TITLE
heatexchanger : remark on model

### ISSUE THREAD

**Issue by GuyDSP** [twiinIT/demos#2]
Adrien, 
Reading the code, I found an element that may be not consistant. 
I think that formula `self.fl_out.T = self.fl_in.T + self.dH / self.cp`  should be `self.fl_out.T = self.fl_in.T + self.heat_flow/ self.cp`
What do you think ?

**Comment by adriendelsalle** [comment]
You're right @GuyDSP, I just merged your PR, thanks!
